import { useContext } from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import 'tailwindcss/tailwind.css'
// components
// import Header from '@/components/Header'
// import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })
import { DataContext } from '@/Context'

export default function Home() {
  const data = useContext(DataContext)
  return (
    <>
   
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="../../dist/output.css" rel="stylesheet"></link> */}
      </Head>
      <main className='bg-white text-red-900 h-screen'>
       <div className="flex h-screen w-screen ">
       <div className='flex gap-5 m-auto'>
              <Link
                href="/dasboard"
                // type="submit"
                onClick={() => {
                  alert('hanya untuk penjual')
                }}
                className="group relative flex w-full justify-center rounded-md bg-yellow-600 px-3 py-2 text-sm font-semibold text-white hover:bg-yellow-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-yellow-600"
              >
                
                  Penjual
                
              </Link>
              <Link
              href="/menu"
                // type="submit"
                className="group relative flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                
                Pembeli
              </Link>
            </div>
       </div>
      </main>
    </>
  )
}
