import { useContext } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import 'tailwindcss/tailwind.css'
// components
import Header from '@/components/Header'
// import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })
import { DataContext } from '@/Context'

export default function Home() {
  const data = useContext(DataContext)
  return (
    <>
    <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="../../dist/output.css" rel="stylesheet"></link> */}
      </Head>
      <main className='bg-white text-red-900 h-screen'>
       <div>
        <p>lorem5
{data.nama}
        </p>
       </div>
      </main>
    </>
  )
}
